{% set version = '1.3.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rttf2pt1
  version: {{ version|replace("-", "_") }}

source:
  fn: Rttf2pt1_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Rttf2pt1_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rttf2pt1/Rttf2pt1_{{ version }}.tar.gz
  sha256: 4eb1f3e0e5bcb11f8e2f6fa7d5ecb3410287291ba538f615872ab78fac20f1a2

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('Rttf2pt1')"           # [not win]
    - "\"%R%\" -e \"library('Rttf2pt1')\""  # [win]

about:
  home: https://github.com/wch/Rttf2pt1
  license: file LICENSE (FOSS)
  summary: Contains the program 'ttf2pt1', for use with the 'extrafont' package. This product
    includes software developed by the 'TTF2PT1' Project and its contributors.
  license_family: OTHER

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - stevierene82
